version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.0.7
      - DB_PORT=3306
      - DB_NAME=dev_management
      - DB_USER=devuser
      - DB_PASSWORD=devpass
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=devpass
      - MYSQL_DATABASE=dev_management
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
